### ISSUE TITLE
switch between speaking and cue voice with different audio devices

### ISSUE THREAD

**Issue by willwade** [AceCentre/Echo#3]
This is fiddly because you have a rather odd UI experience for the end user to choose the audio outputs - and im not sure what will happen between sessions (e.g. unpluging or BT devices reconnecting)

```swift

import AVFoundation

class AudioController {
    var cueAudioPlayer: AVAudioPlayer?
    var mainAudioPlayer: AVAudioPlayer?
    
    init() {
        // Initialize AVAudioSession
        do {
            let audioSession = AVAudioSession.sharedInstance()
            try audioSession.setCategory(.playAndRecord, options: [.defaultToSpeaker])
            try audioSession.setActive(true)
        } catch {
            print("Failed to set up audio session: \(error)")
        }
    }
    
    func listAvailableOutputs() {
        let currentRoute = AVAudioSession.sharedInstance().currentRoute
        for output in currentRoute.outputs {
            print(output.portName)
        }
    }
    
    func showAudioRoutePicker() {
        let audioSession = AVAudioSession.sharedInstance()
        audioSession.showRoutePicker()
    }
    
    func playCueAudio(from cueURL: URL) {
        do {
            cueAudioPlayer = try AVAudioPlayer(contentsOf: cueURL)
            cueAudioPlayer?.play()
        } catch {
            print("Failed to initialize cue audio player: \(error)")
        }
    }
    
    func playMainAudio(from mainURL: URL) {
        do {
            mainAudioPlayer = try AVAudioPlayer(contentsOf: mainURL)
            mainAudioPlayer?.play()
        } catch {
            print("Failed to initialize main audio player: \(error)")
        }
    }
}
```

usage 

```swift

let audioController = AudioController()

// List available audio outputs
audioController.listAvailableOutputs()

// Show audio route picker (user can manually select output)
audioController.showAudioRoutePicker()

// Play cue and main audio
if let cueURL = Bundle.main.url(forResource: "cueAudio", withExtension: "mp3"),
   let mainURL = Bundle.main.url(forResource: "mainAudio", withExtension: "mp3") {
    audioController.playCueAudio(from: cueURL)
    audioController.playMainAudio(from: mainURL)
}
```

The alternative is Audio Units

```swift

import AudioToolbox

class AudioUnitController {
    var audioUnit: AudioUnit?
    
    init() {
        var audioComponentDescription = AudioComponentDescription(
            componentType: kAudioUnitType_Output,
            componentSubType: kAudioUnitSubType_RemoteIO,
            componentManufacturer: kAudioUnitManufacturer_Apple,
            componentFlags: 0,
            componentFlagsMask: 0)
        
        let audioComponent = AudioComponentFindNext(nil, &audioComponentDescription)
        
        AudioComponentInstanceNew(audioComponent!, &audioUnit)
        
        var one: UInt32 = 1
        AudioUnitSetProperty(audioUnit!,
                             kAudioOutputUnitProperty_EnableIO,
                             kAudioUnitScope_Output,
                             0,
                             &one,
                             UInt32(MemoryLayout<UInt32>.size))
        
        AudioUnitInitialize(audioUnit!)
    }
    
    func start() {
        AudioOutputUnitStart(audioUnit!)
    }
    
    func stop() {
        AudioOutputUnitStop(audioUnit!)
    }
    
    // Add your audio processing logic here
    // ...
}
```

and usage

```swift
let audioUnitController = AudioUnitController()
audioUnitController.start()

// Do other tasks...

audioUnitController.stop()
```

To switch between different audio outputs, you'd still face the same limitations as with AVAudioSession, as iOS doesn't provide a straightforward API for programmatically switching audio outputs. You can, however, use AVAudioSession in conjunction with Audio Units to show the route picker to the user for manual selection.

```swift
AVAudioSession.sharedInstance().showRoutePicker()
```

**Comment by gavinhenderson** [comment]
So after some pretty intense digging, I don't think its possible to pull this off in iOS currently.
 
Confusingly I there is some APIs around the Midi stuff that look promising at first look. However, my understanding is that those APIs only apply when you have a separate Midi device connected that is compatible with Apples stuff and that device itself has multiple outputs as an option. In that senario Apple is still outputting all audio to the midi device but the midi device is doing.

Don't take anything I am saying for certainty, its a complex and frankly poorly documented issue. Its also hard to research as its not easy to come up with clear terms about.

For the most part though all the examples online tend to be based around have different audio layers in the app so you can control them separately, volume, effects etc. But importantly, they all end up going through the same 'route' out. Showing the audio picker can change that route but it changes it globally for the whole app by the looks of it.

I am going to reach out to a dev at apple and ask them if what we are trying to achieve is possible, as they will be able to confirm with more certainty. For now I am going to leave this issue open but I dont think it should block release because its going to be a long ongoing saga i think.

**Comment by willwade** [comment]
Yeah. The r&d is worth it. Don't let it block for sure. 

One thing to add. We did have it working successfully in pasco but only between a wired headphone jack and something else. I say we did - it was definitely flaky.

**Comment by gavinhenderson** [comment]
> One thing to add. We did have it working successfully in pasco but only between a wired headphone jack and something else. I say we did - it was definitely flaky.

Hmm that is interesting. I will have to a dig around for that code and see if i can copy it

**Comment by gavinhenderson** [comment]
Closing in favour of #37
